/*
 * Created by Ubique Innovation AG
 * https://www.ubique.ch
 * Copyright (c) 2020. All rights reserved.
 */

CREATE TABLE t_diary_entry
(
    pk_diary_entry_id integer                  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name              character varying(255)   NOT NULL,
    location          character varying(255)   NOT NULL,
    room              character varying(255)   NOT NULL,
    venue_type        character varying(50)    NOT NULL,
    checkin_time      timestamp with time zone NOT NULL,
    checkout_time     timestamp with time zone NOT NULL,
    CONSTRAINT pk_t_diary_entry PRIMARY KEY (pk_diary_entry_id)
);