GET {{baseUrl}}/v1/traceKeys?lastKeyBundleTag=1605776400000
Accept: application/json

###
POST {{baseUrl}}/v1/debug/traceKey
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="ctx"

zFpds-bkQTfpx9qi5zzPzjkeZtDhrFgI_V_uqerB9Ww77Lf3w-ASMi8HtZNRx_e6ArBVYBfa5_YBEbt43Yg54TaRT9TGwYJG6T2FTn1nQ4zIWNDAiWIw44XWL0KTELecU-ctPAoBWb30j_nQICpE_7XObn41IBf-RQbbm5YpvliLmPhfI4-SdI3eRmA
--WebAppBoundary
Content-Disposition: form-data; name="startTime"

1604542547000
--WebAppBoundary
Content-Disposition: form-data; name="endTime"

1604562547000
--WebAppBoundary--

###