// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProblematicEventWrapper.proto

package ch.ubique.n2step.sdk.backend.model;

public final class ProblematicEventWrapperOuterClass {
  private ProblematicEventWrapperOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProblematicEventWrapperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapper)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 version = 1;</code>
     * @return Whether the version field is set.
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 1;</code>
     * @return The version.
     */
    int getVersion();

    /**
     * <code>repeated .ch.ubique.n2step.sdk.backend.model.ProblematicEvent events = 2;</code>
     */
    java.util.List<ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent> 
        getEventsList();
    /**
     * <code>repeated .ch.ubique.n2step.sdk.backend.model.ProblematicEvent events = 2;</code>
     */
    ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent getEvents(int index);
    /**
     * <code>repeated .ch.ubique.n2step.sdk.backend.model.ProblematicEvent events = 2;</code>
     */
    int getEventsCount();
    /**
     * <code>repeated .ch.ubique.n2step.sdk.backend.model.ProblematicEvent events = 2;</code>
     */
    java.util.List<? extends ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventOrBuilder> 
        getEventsOrBuilderList();
    /**
     * <code>repeated .ch.ubique.n2step.sdk.backend.model.ProblematicEvent events = 2;</code>
     */
    ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventOrBuilder getEventsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapper}
   */
  public static final class ProblematicEventWrapper extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapper)
      ProblematicEventWrapperOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProblematicEventWrapper.newBuilder() to construct.
    private ProblematicEventWrapper(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProblematicEventWrapper() {
      events_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ProblematicEventWrapper();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProblematicEventWrapper(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                events_ = new java.util.ArrayList<ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent>();
                mutable_bitField0_ |= 0x00000002;
              }
              events_.add(
                  input.readMessage(ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          events_ = java.util.Collections.unmodifiableList(events_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.internal_static_ch_ubique_n2step_sdk_backend_model_ProblematicEventWrapper_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.internal_static_ch_ubique_n2step_sdk_backend_model_ProblematicEventWrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper.class, ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper.Builder.class);
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required int32 version = 1;</code>
     * @return Whether the version field is set.
     */
    @java.lang.Override
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }

    public static final int EVENTS_FIELD_NUMBER = 2;
    private java.util.List<ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent> events_;
    /**
     * <code>repeated .ch.ubique.n2step.sdk.backend.model.ProblematicEvent events = 2;</code>
     */
    @java.lang.Override
    public java.util.List<ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent> getEventsList() {
      return events_;
    }
    /**
     * <code>repeated .ch.ubique.n2step.sdk.backend.model.ProblematicEvent events = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventOrBuilder> 
        getEventsOrBuilderList() {
      return events_;
    }
    /**
     * <code>repeated .ch.ubique.n2step.sdk.backend.model.ProblematicEvent events = 2;</code>
     */
    @java.lang.Override
    public int getEventsCount() {
      return events_.size();
    }
    /**
     * <code>repeated .ch.ubique.n2step.sdk.backend.model.ProblematicEvent events = 2;</code>
     */
    @java.lang.Override
    public ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent getEvents(int index) {
      return events_.get(index);
    }
    /**
     * <code>repeated .ch.ubique.n2step.sdk.backend.model.ProblematicEvent events = 2;</code>
     */
    @java.lang.Override
    public ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventOrBuilder getEventsOrBuilder(
        int index) {
      return events_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getEventsCount(); i++) {
        if (!getEvents(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, version_);
      }
      for (int i = 0; i < events_.size(); i++) {
        output.writeMessage(2, events_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      for (int i = 0; i < events_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, events_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper)) {
        return super.equals(obj);
      }
      ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper other = (ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper) obj;

      if (hasVersion() != other.hasVersion()) return false;
      if (hasVersion()) {
        if (getVersion()
            != other.getVersion()) return false;
      }
      if (!getEventsList()
          .equals(other.getEventsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion();
      }
      if (getEventsCount() > 0) {
        hash = (37 * hash) + EVENTS_FIELD_NUMBER;
        hash = (53 * hash) + getEventsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapper}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapper)
        ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.internal_static_ch_ubique_n2step_sdk_backend_model_ProblematicEventWrapper_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.internal_static_ch_ubique_n2step_sdk_backend_model_ProblematicEventWrapper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper.class, ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper.Builder.class);
      }

      // Construct using ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEventsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (eventsBuilder_ == null) {
          events_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          eventsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.internal_static_ch_ubique_n2step_sdk_backend_model_ProblematicEventWrapper_descriptor;
      }

      @java.lang.Override
      public ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper getDefaultInstanceForType() {
        return ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper.getDefaultInstance();
      }

      @java.lang.Override
      public ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper build() {
        ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper buildPartial() {
        ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper result = new ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.version_ = version_;
          to_bitField0_ |= 0x00000001;
        }
        if (eventsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            events_ = java.util.Collections.unmodifiableList(events_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.events_ = events_;
        } else {
          result.events_ = eventsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper) {
          return mergeFrom((ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper other) {
        if (other == ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (eventsBuilder_ == null) {
          if (!other.events_.isEmpty()) {
            if (events_.isEmpty()) {
              events_ = other.events_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureEventsIsMutable();
              events_.addAll(other.events_);
            }
            onChanged();
          }
        } else {
          if (!other.events_.isEmpty()) {
            if (eventsBuilder_.isEmpty()) {
              eventsBuilder_.dispose();
              eventsBuilder_ = null;
              events_ = other.events_;
              bitField0_ = (bitField0_ & ~0x00000002);
              eventsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEventsFieldBuilder() : null;
            } else {
              eventsBuilder_.addAllMessages(other.events_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasVersion()) {
          return false;
        }
        for (int i = 0; i < getEventsCount(); i++) {
          if (!getEvents(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int version_ ;
      /**
       * <code>required int32 version = 1;</code>
       * @return Whether the version field is set.
       */
      @java.lang.Override
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 version = 1;</code>
       * @return The version.
       */
      @java.lang.Override
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required int32 version = 1;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent> events_ =
        java.util.Collections.emptyList();
      private void ensureEventsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          events_ = new java.util.ArrayList<ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent>(events_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent, ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent.Builder, ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventOrBuilder> eventsBuilder_;

      /**
       * <code>repeated .ch.ubique.n2step.sdk.backend.model.ProblematicEvent events = 2;</code>
       */
      public java.util.List<ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent> getEventsList() {
        if (eventsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(events_);
        } else {
          return eventsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ch.ubique.n2step.sdk.backend.model.ProblematicEvent events = 2;</code>
       */
      public int getEventsCount() {
        if (eventsBuilder_ == null) {
          return events_.size();
        } else {
          return eventsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ch.ubique.n2step.sdk.backend.model.ProblematicEvent events = 2;</code>
       */
      public ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent getEvents(int index) {
        if (eventsBuilder_ == null) {
          return events_.get(index);
        } else {
          return eventsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ch.ubique.n2step.sdk.backend.model.ProblematicEvent events = 2;</code>
       */
      public Builder setEvents(
          int index, ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent value) {
        if (eventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventsIsMutable();
          events_.set(index, value);
          onChanged();
        } else {
          eventsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ch.ubique.n2step.sdk.backend.model.ProblematicEvent events = 2;</code>
       */
      public Builder setEvents(
          int index, ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent.Builder builderForValue) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.set(index, builderForValue.build());
          onChanged();
        } else {
          eventsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ch.ubique.n2step.sdk.backend.model.ProblematicEvent events = 2;</code>
       */
      public Builder addEvents(ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent value) {
        if (eventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventsIsMutable();
          events_.add(value);
          onChanged();
        } else {
          eventsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ch.ubique.n2step.sdk.backend.model.ProblematicEvent events = 2;</code>
       */
      public Builder addEvents(
          int index, ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent value) {
        if (eventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventsIsMutable();
          events_.add(index, value);
          onChanged();
        } else {
          eventsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ch.ubique.n2step.sdk.backend.model.ProblematicEvent events = 2;</code>
       */
      public Builder addEvents(
          ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent.Builder builderForValue) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.add(builderForValue.build());
          onChanged();
        } else {
          eventsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ch.ubique.n2step.sdk.backend.model.ProblematicEvent events = 2;</code>
       */
      public Builder addEvents(
          int index, ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent.Builder builderForValue) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.add(index, builderForValue.build());
          onChanged();
        } else {
          eventsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ch.ubique.n2step.sdk.backend.model.ProblematicEvent events = 2;</code>
       */
      public Builder addAllEvents(
          java.lang.Iterable<? extends ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent> values) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, events_);
          onChanged();
        } else {
          eventsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ch.ubique.n2step.sdk.backend.model.ProblematicEvent events = 2;</code>
       */
      public Builder clearEvents() {
        if (eventsBuilder_ == null) {
          events_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          eventsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ch.ubique.n2step.sdk.backend.model.ProblematicEvent events = 2;</code>
       */
      public Builder removeEvents(int index) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.remove(index);
          onChanged();
        } else {
          eventsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ch.ubique.n2step.sdk.backend.model.ProblematicEvent events = 2;</code>
       */
      public ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent.Builder getEventsBuilder(
          int index) {
        return getEventsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ch.ubique.n2step.sdk.backend.model.ProblematicEvent events = 2;</code>
       */
      public ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventOrBuilder getEventsOrBuilder(
          int index) {
        if (eventsBuilder_ == null) {
          return events_.get(index);  } else {
          return eventsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ch.ubique.n2step.sdk.backend.model.ProblematicEvent events = 2;</code>
       */
      public java.util.List<? extends ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventOrBuilder> 
           getEventsOrBuilderList() {
        if (eventsBuilder_ != null) {
          return eventsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(events_);
        }
      }
      /**
       * <code>repeated .ch.ubique.n2step.sdk.backend.model.ProblematicEvent events = 2;</code>
       */
      public ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent.Builder addEventsBuilder() {
        return getEventsFieldBuilder().addBuilder(
            ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent.getDefaultInstance());
      }
      /**
       * <code>repeated .ch.ubique.n2step.sdk.backend.model.ProblematicEvent events = 2;</code>
       */
      public ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent.Builder addEventsBuilder(
          int index) {
        return getEventsFieldBuilder().addBuilder(
            index, ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent.getDefaultInstance());
      }
      /**
       * <code>repeated .ch.ubique.n2step.sdk.backend.model.ProblematicEvent events = 2;</code>
       */
      public java.util.List<ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent.Builder> 
           getEventsBuilderList() {
        return getEventsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent, ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent.Builder, ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventOrBuilder> 
          getEventsFieldBuilder() {
        if (eventsBuilder_ == null) {
          eventsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent, ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent.Builder, ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventOrBuilder>(
                  events_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          events_ = null;
        }
        return eventsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapper)
    }

    // @@protoc_insertion_point(class_scope:ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapper)
    private static final ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper();
    }

    public static ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ProblematicEventWrapper>
        PARSER = new com.google.protobuf.AbstractParser<ProblematicEventWrapper>() {
      @java.lang.Override
      public ProblematicEventWrapper parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProblematicEventWrapper(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProblematicEventWrapper> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProblematicEventWrapper> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProblematicEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ch.ubique.n2step.sdk.backend.model.ProblematicEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes secretKey = 1;</code>
     * @return Whether the secretKey field is set.
     */
    boolean hasSecretKey();
    /**
     * <code>required bytes secretKey = 1;</code>
     * @return The secretKey.
     */
    com.google.protobuf.ByteString getSecretKey();

    /**
     * <code>required int64 startTime = 2;</code>
     * @return Whether the startTime field is set.
     */
    boolean hasStartTime();
    /**
     * <code>required int64 startTime = 2;</code>
     * @return The startTime.
     */
    long getStartTime();

    /**
     * <code>required int64 endTime = 3;</code>
     * @return Whether the endTime field is set.
     */
    boolean hasEndTime();
    /**
     * <code>required int64 endTime = 3;</code>
     * @return The endTime.
     */
    long getEndTime();

    /**
     * <code>optional bytes message = 4;</code>
     * @return Whether the message field is set.
     */
    boolean hasMessage();
    /**
     * <code>optional bytes message = 4;</code>
     * @return The message.
     */
    com.google.protobuf.ByteString getMessage();
  }
  /**
   * Protobuf type {@code ch.ubique.n2step.sdk.backend.model.ProblematicEvent}
   */
  public static final class ProblematicEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ch.ubique.n2step.sdk.backend.model.ProblematicEvent)
      ProblematicEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProblematicEvent.newBuilder() to construct.
    private ProblematicEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProblematicEvent() {
      secretKey_ = com.google.protobuf.ByteString.EMPTY;
      message_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ProblematicEvent();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProblematicEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              bitField0_ |= 0x00000001;
              secretKey_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              startTime_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              endTime_ = input.readInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              message_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.internal_static_ch_ubique_n2step_sdk_backend_model_ProblematicEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.internal_static_ch_ubique_n2step_sdk_backend_model_ProblematicEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent.class, ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent.Builder.class);
    }

    private int bitField0_;
    public static final int SECRETKEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString secretKey_;
    /**
     * <code>required bytes secretKey = 1;</code>
     * @return Whether the secretKey field is set.
     */
    @java.lang.Override
    public boolean hasSecretKey() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required bytes secretKey = 1;</code>
     * @return The secretKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSecretKey() {
      return secretKey_;
    }

    public static final int STARTTIME_FIELD_NUMBER = 2;
    private long startTime_;
    /**
     * <code>required int64 startTime = 2;</code>
     * @return Whether the startTime field is set.
     */
    @java.lang.Override
    public boolean hasStartTime() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int64 startTime = 2;</code>
     * @return The startTime.
     */
    @java.lang.Override
    public long getStartTime() {
      return startTime_;
    }

    public static final int ENDTIME_FIELD_NUMBER = 3;
    private long endTime_;
    /**
     * <code>required int64 endTime = 3;</code>
     * @return Whether the endTime field is set.
     */
    @java.lang.Override
    public boolean hasEndTime() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int64 endTime = 3;</code>
     * @return The endTime.
     */
    @java.lang.Override
    public long getEndTime() {
      return endTime_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString message_;
    /**
     * <code>optional bytes message = 4;</code>
     * @return Whether the message field is set.
     */
    @java.lang.Override
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bytes message = 4;</code>
     * @return The message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getMessage() {
      return message_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSecretKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStartTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEndTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(1, secretKey_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, startTime_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt64(3, endTime_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBytes(4, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, secretKey_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, startTime_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, endTime_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent)) {
        return super.equals(obj);
      }
      ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent other = (ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent) obj;

      if (hasSecretKey() != other.hasSecretKey()) return false;
      if (hasSecretKey()) {
        if (!getSecretKey()
            .equals(other.getSecretKey())) return false;
      }
      if (hasStartTime() != other.hasStartTime()) return false;
      if (hasStartTime()) {
        if (getStartTime()
            != other.getStartTime()) return false;
      }
      if (hasEndTime() != other.hasEndTime()) return false;
      if (hasEndTime()) {
        if (getEndTime()
            != other.getEndTime()) return false;
      }
      if (hasMessage() != other.hasMessage()) return false;
      if (hasMessage()) {
        if (!getMessage()
            .equals(other.getMessage())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSecretKey()) {
        hash = (37 * hash) + SECRETKEY_FIELD_NUMBER;
        hash = (53 * hash) + getSecretKey().hashCode();
      }
      if (hasStartTime()) {
        hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getStartTime());
      }
      if (hasEndTime()) {
        hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getEndTime());
      }
      if (hasMessage()) {
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ch.ubique.n2step.sdk.backend.model.ProblematicEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ch.ubique.n2step.sdk.backend.model.ProblematicEvent)
        ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.internal_static_ch_ubique_n2step_sdk_backend_model_ProblematicEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.internal_static_ch_ubique_n2step_sdk_backend_model_ProblematicEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent.class, ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent.Builder.class);
      }

      // Construct using ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        secretKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        startTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        endTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        message_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.internal_static_ch_ubique_n2step_sdk_backend_model_ProblematicEvent_descriptor;
      }

      @java.lang.Override
      public ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent getDefaultInstanceForType() {
        return ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent.getDefaultInstance();
      }

      @java.lang.Override
      public ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent build() {
        ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent buildPartial() {
        ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent result = new ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.secretKey_ = secretKey_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.startTime_ = startTime_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.endTime_ = endTime_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent) {
          return mergeFrom((ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent other) {
        if (other == ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent.getDefaultInstance()) return this;
        if (other.hasSecretKey()) {
          setSecretKey(other.getSecretKey());
        }
        if (other.hasStartTime()) {
          setStartTime(other.getStartTime());
        }
        if (other.hasEndTime()) {
          setEndTime(other.getEndTime());
        }
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasSecretKey()) {
          return false;
        }
        if (!hasStartTime()) {
          return false;
        }
        if (!hasEndTime()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString secretKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes secretKey = 1;</code>
       * @return Whether the secretKey field is set.
       */
      @java.lang.Override
      public boolean hasSecretKey() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required bytes secretKey = 1;</code>
       * @return The secretKey.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getSecretKey() {
        return secretKey_;
      }
      /**
       * <code>required bytes secretKey = 1;</code>
       * @param value The secretKey to set.
       * @return This builder for chaining.
       */
      public Builder setSecretKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        secretKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes secretKey = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSecretKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        secretKey_ = getDefaultInstance().getSecretKey();
        onChanged();
        return this;
      }

      private long startTime_ ;
      /**
       * <code>required int64 startTime = 2;</code>
       * @return Whether the startTime field is set.
       */
      @java.lang.Override
      public boolean hasStartTime() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int64 startTime = 2;</code>
       * @return The startTime.
       */
      @java.lang.Override
      public long getStartTime() {
        return startTime_;
      }
      /**
       * <code>required int64 startTime = 2;</code>
       * @param value The startTime to set.
       * @return This builder for chaining.
       */
      public Builder setStartTime(long value) {
        bitField0_ |= 0x00000002;
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 startTime = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        startTime_ = 0L;
        onChanged();
        return this;
      }

      private long endTime_ ;
      /**
       * <code>required int64 endTime = 3;</code>
       * @return Whether the endTime field is set.
       */
      @java.lang.Override
      public boolean hasEndTime() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required int64 endTime = 3;</code>
       * @return The endTime.
       */
      @java.lang.Override
      public long getEndTime() {
        return endTime_;
      }
      /**
       * <code>required int64 endTime = 3;</code>
       * @param value The endTime to set.
       * @return This builder for chaining.
       */
      public Builder setEndTime(long value) {
        bitField0_ |= 0x00000004;
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 endTime = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEndTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        endTime_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString message_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes message = 4;</code>
       * @return Whether the message field is set.
       */
      @java.lang.Override
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional bytes message = 4;</code>
       * @return The message.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getMessage() {
        return message_;
      }
      /**
       * <code>optional bytes message = 4;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes message = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000008);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ch.ubique.n2step.sdk.backend.model.ProblematicEvent)
    }

    // @@protoc_insertion_point(class_scope:ch.ubique.n2step.sdk.backend.model.ProblematicEvent)
    private static final ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent();
    }

    public static ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ProblematicEvent>
        PARSER = new com.google.protobuf.AbstractParser<ProblematicEvent>() {
      @java.lang.Override
      public ProblematicEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProblematicEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProblematicEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProblematicEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ch.ubique.n2step.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ch_ubique_n2step_sdk_backend_model_ProblematicEventWrapper_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ch_ubique_n2step_sdk_backend_model_ProblematicEventWrapper_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ch_ubique_n2step_sdk_backend_model_ProblematicEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ch_ubique_n2step_sdk_backend_model_ProblematicEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035ProblematicEventWrapper.proto\022\"ch.ubiq" +
      "ue.n2step.sdk.backend.model\"p\n\027Problemat" +
      "icEventWrapper\022\017\n\007version\030\001 \002(\005\022D\n\006event" +
      "s\030\002 \003(\01324.ch.ubique.n2step.sdk.backend.m" +
      "odel.ProblematicEvent\"Z\n\020ProblematicEven" +
      "t\022\021\n\tsecretKey\030\001 \002(\014\022\021\n\tstartTime\030\002 \002(\003\022" +
      "\017\n\007endTime\030\003 \002(\003\022\017\n\007message\030\004 \001(\014B$\n\"ch." +
      "ubique.n2step.sdk.backend.model"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ch_ubique_n2step_sdk_backend_model_ProblematicEventWrapper_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ch_ubique_n2step_sdk_backend_model_ProblematicEventWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ch_ubique_n2step_sdk_backend_model_ProblematicEventWrapper_descriptor,
        new java.lang.String[] { "Version", "Events", });
    internal_static_ch_ubique_n2step_sdk_backend_model_ProblematicEvent_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ch_ubique_n2step_sdk_backend_model_ProblematicEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ch_ubique_n2step_sdk_backend_model_ProblematicEvent_descriptor,
        new java.lang.String[] { "SecretKey", "StartTime", "EndTime", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
